package:
  name: libbluetooth-headers
  version: 5.56

source:
  url: http://www.kernel.org/pub/linux/bluetooth/bluez-5.56.tar.xz
  sha256: 59c4dba9fc8aae2a6a5f8f12f19bc1b0c2dc27355c7ca3123eed3fe6bd7d0b9d

about:
  home: http://www.bluez.org/
  summary: "libbluetooth header files"
  